const $ = (id) => document.getElementById(id);

const PRESETS = {
  quick: { maxPages:30, viewports:{current:false,desktop:true,tablet:false,mobile:true}, collect:{console:true,network:true,performance:true,accessibility:false,dom:true,designSystem:false,axTree:false,tracing:false} },
  full: { maxPages:100, viewports:{current:false,desktop:true,tablet:true,mobile:true}, collect:{console:true,network:true,performance:true,accessibility:true,dom:true,designSystem:true,axTree:false,tracing:false} },
  deep: { maxPages:30, viewports:{current:true,desktop:true,tablet:true,mobile:true}, collect:{console:true,network:true,performance:true,accessibility:true,dom:true,designSystem:true,axTree:true,tracing:true} }
};
let activeOrigin = null;
function selectedMode(){ return document.querySelector('input[name="mode"]:checked')?.value || 'full'; }
function parseHttpUrl(raw){ try{ const url=new URL(raw); if(!['http:','https:'].includes(url.protocol)) return null; return url;}catch{return null;} }
function applyPreset(mode,preserveMaxPages=false){ const p=PRESETS[mode]; if(!preserveMaxPages) $('maxPages').value=p.maxPages; $('viewportCurrent').checked=p.viewports.current; $('viewportDesktop').checked=p.viewports.desktop; $('viewportTablet').checked=p.viewports.tablet; $('viewportMobile').checked=p.viewports.mobile; $('run').textContent=`▶ Crawler et diagnostiquer · ${mode[0].toUpperCase()}${mode.slice(1)}`; $('modeHint').textContent=mode==='full'?'Full recommandé':mode==='quick'?'Rapide':'Très détaillé'; document.querySelectorAll('.mode-card').forEach(x=>x.classList.toggle('selected',x.querySelector('input')?.checked)); }
function collectConfig(overrides={}){ const mode=overrides.mode||selectedMode(); const p=PRESETS[mode]; return {mode,startUrl:$('startUrl').value.trim(),projectName:$('projectName').value.trim(),gitBranch:$('gitBranch').value.trim(),gitCommit:$('gitCommit').value.trim(),maxPages:Math.min(500,Math.max(1,Number($('maxPages').value)||p.maxPages)),settleMs:Math.min(10000,Math.max(200,Number($('settleMs').value)||900)),viewportCurrent:$('viewportCurrent').checked,viewportDesktop:$('viewportDesktop').checked,viewportTablet:$('viewportTablet').checked,viewportMobile:$('viewportMobile').checked,includeQuery:$('includeQuery').checked,includeHash:$('includeHash').checked,lazyScroll:$('lazyScroll').checked,rawDomSnapshot:$('rawDomSnapshot').checked,extraRoutes:$('extraRoutes').value,ignorePatterns:$('ignorePatterns').value,collect:{...p.collect},...overrides}; }
function restore(c){ if(!c)return; const ids=['startUrl','projectName','gitBranch','gitCommit','maxPages','settleMs','extraRoutes','ignorePatterns','includeQuery','includeHash','lazyScroll','rawDomSnapshot','viewportCurrent','viewportDesktop','viewportTablet','viewportMobile']; for(const id of ids){ if(!(id in c))continue; const el=$(id); if(el.type==='checkbox')el.checked=Boolean(c[id]); else el.value=c[id]??'';} const mode=c.mode||'full'; const radio=document.querySelector(`input[name="mode"][value="${mode}"]`); if(radio)radio.checked=true; applyPreset(mode,true); for(const id of ['viewportCurrent','viewportDesktop','viewportTablet','viewportMobile']) if(id in c) $(id).checked=Boolean(c[id]); }
let persistConfigTimer=null; function persistConfigSoon(){ clearTimeout(persistConfigTimer); persistConfigTimer=setTimeout(()=>{chrome.storage.local.set({lastConfig:collectConfig()}).catch(()=>{});},180); }
async function init(){ const [active]=await chrome.tabs.query({active:true,currentWindow:true}); const stored=await chrome.storage.local.get(['lastConfig','captureStatus']); if(stored.lastConfig)restore(stored.lastConfig); else applyPreset('full'); if(active?.url&&/^https?:\/\//i.test(active.url)){ if(!stored.lastConfig?.startUrl||parseHttpUrl(stored.lastConfig.startUrl)?.origin!==new URL(active.url).origin){$('startUrl').value=active.url;if(!$('projectName').value)$('projectName').value=guessProjectName(active.url);} activeOrigin=new URL(active.url).origin;} if(stored.captureStatus?.state==='running')renderStatus(stored.captureStatus); await refreshAnnotations(); await refreshHistory(); persistConfigSoon(); }
function guessProjectName(raw){try{return new URL(raw).hostname.replace(/^www\./,'').split('.')[0].replace(/[-_]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase());}catch{return '';}}
async function startJob(config,{targetTabId=null,useExistingTab=false,singlePage=false}={}){ $('error').textContent=''; $('run').disabled=true; const parsed=parseHttpUrl(config.startUrl); if(!parsed){$('error').textContent='Entre une URL HTTP/HTTPS valide.';$('run').disabled=false;return;} if(!config.viewportCurrent&&!config.viewportDesktop&&!config.viewportTablet&&!config.viewportMobile){$('error').textContent='Sélectionne au moins un viewport.';$('run').disabled=false;return;} let target=targetTabId; if(!target){const created=await chrome.tabs.create({url:config.startUrl,active:false});target=created.id;} const job={config,targetTabId:target,useExistingTab,singlePage,createdAt:Date.now()}; await chrome.storage.local.set({lastConfig:config,captureJob:job,captureStatus:{state:'starting',mode:config.mode,currentPage:config.startUrl}}); await chrome.tabs.create({url:chrome.runtime.getURL('runner.html'),active:false}); $('live').classList.remove('hidden'); $('run').disabled=true; }
$('run').addEventListener('click',async()=>{try{await startJob(collectConfig());}catch(e){$('error').textContent=e?.message||String(e);$('run').disabled=false;}});
$('captureState').addEventListener('click',async()=>{try{const [active]=await chrome.tabs.query({active:true,currentWindow:true});if(!active?.id||!/^https?:\/\//i.test(active.url||''))throw new Error('Ouvre une page HTTP/HTTPS à capturer.');const base=collectConfig({mode:'full'});const config={...base,startUrl:active.url,maxPages:1,viewportCurrent:true,viewportDesktop:false,viewportTablet:false,viewportMobile:false,projectName:base.projectName||guessProjectName(active.url),captureLabel:'current-state'};await startJob(config,{targetTabId:active.id,useExistingTab:true,singlePage:true});}catch(e){$('error').textContent=e?.message||String(e);}});
for(const radio of document.querySelectorAll('input[name="mode"]')) radio.addEventListener('change',()=>{applyPreset(selectedMode());persistConfigSoon();});
for(const el of document.querySelectorAll('input:not([name="mode"]), select, textarea')){el.addEventListener(el.tagName==='INPUT'&&!['checkbox','radio'].includes(el.type)?'input':'change',persistConfigSoon);if(el.tagName==='TEXTAREA')el.addEventListener('input',persistConfigSoon);}
chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;if(changes.captureStatus?.newValue)renderStatus(changes.captureStatus.newValue);if(changes.diagnosticHistory)refreshHistory();if(changes.uxAnnotations)refreshAnnotations();});
function renderStatus(s){if(!s)return;$('live').classList.toggle('hidden',!['starting','running','done','failed'].includes(s.state));$('liveId').textContent=s.diagnosticId||'Création de l’ID…';$('liveMode').textContent=(s.mode||'full').toUpperCase();$('visited').textContent=s.visited??0;$('queued').textContent=s.queued??0;$('captures').textContent=s.captures??0;$('errors').textContent=s.errors??0;$('currentPage').textContent=s.state==='done'?`Terminé · ${s.filename||''}`:s.currentPage||s.state;$('progressBar').style.width=`${Math.max(0,Math.min(100,s.progress??(s.state==='done'?100:0)))}%`;const busy=['starting','running'].includes(s.state);$('run').disabled=busy;$('captureState').disabled=busy;$('markIssue').disabled=busy;}
async function refreshHistory(){const {diagnosticHistory=[]}=await chrome.storage.local.get('diagnosticHistory');const items=diagnosticHistory.slice(0,8);$('history').innerHTML=items.length?items.map(d=>`<button class="history-item" data-id="${escapeHtml(d.diagnosticId)}"><span><strong>${escapeHtml(d.diagnosticId)}</strong><span>${escapeHtml(d.projectName||d.host)} · ${escapeHtml((d.mode||'').toUpperCase())} · ${new Date(d.finishedAt||d.startedAt).toLocaleString()}</span></span><span class="history-score">${d.scores?.overall??'—'}</span></button>`).join(''):'<p class="muted">Aucun diagnostic enregistré.</p>';for(const el of $('history').querySelectorAll('[data-id]'))el.addEventListener('click',()=>chrome.tabs.create({url:chrome.runtime.getURL(`report.html?id=${encodeURIComponent(el.dataset.id)}`)}));}
$('refreshHistory').addEventListener('click',refreshHistory);
async function refreshAnnotations(){const {uxAnnotations=[]}=await chrome.storage.local.get('uxAnnotations');const raw=parseHttpUrl($('startUrl').value)?.origin||activeOrigin;const count=uxAnnotations.filter(x=>!raw||x.origin===raw).length;$('annotationCount').textContent=count?`${count} annotation(s) seront incluses dans le prochain diagnostic de ce site.`:'Aucune annotation en attente.';}
$('clearAnnotations').addEventListener('click',async()=>{const {uxAnnotations=[]}=await chrome.storage.local.get('uxAnnotations');const origin=parseHttpUrl($('startUrl').value)?.origin||activeOrigin;await chrome.storage.local.set({uxAnnotations:uxAnnotations.filter(x=>x.origin!==origin)});});$('startUrl').addEventListener('change',refreshAnnotations);
$('markIssue').addEventListener('click',async()=>{$('error').textContent='';$('markIssue').disabled=true;$('markIssue').textContent='Clique un élément sur la page…';try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!/^https?:\/\//i.test(tab.url||''))throw new Error('Ouvre la page du site concerné.');const [{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:selectElementOnPage});if(!result)return;const note=prompt('Quel est le problème ou le doute UX sur cet élément ?','')?.trim();if(!note)return;const dataUrl=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'png'});const crop=await cropScreenshot(dataUrl,result.rect,result.viewport);const origin=new URL(tab.url).origin;const {uxAnnotations=[]}=await chrome.storage.local.get('uxAnnotations');const annotation={id:`UX-${Date.now().toString(36).toUpperCase()}`,origin,url:tab.url,createdAt:new Date().toISOString(),selector:result.selector,element:{tag:result.tag,role:result.role,text:result.text,ariaLabel:result.ariaLabel,rect:result.rect},note,screenshotDataUrl:crop};await chrome.storage.local.set({uxAnnotations:[...uxAnnotations,annotation].slice(-30)});}catch(e){$('error').textContent=e?.message||String(e);}finally{$('markIssue').disabled=false;$('markIssue').textContent='🎯 Marquer un problème UX';}});
function selectElementOnPage(){return new Promise(resolve=>{const overlay=document.createElement('div');Object.assign(overlay.style,{position:'fixed',zIndex:'2147483647',pointerEvents:'none',border:'2px solid #7c3aed',background:'rgba(124,58,237,.12)',borderRadius:'4px',display:'none'});document.documentElement.appendChild(overlay);const selectorFor=el=>{if(el.id)return`#${CSS.escape(el.id)}`;const testId=el.getAttribute('data-testid');if(testId)return`[data-testid="${CSS.escape(testId)}"]`;const parts=[];let cur=el;while(cur&&cur.nodeType===1&&parts.length<5){let part=cur.localName;const cls=[...cur.classList].filter(x=>/^[a-zA-Z_-][\w-]*$/.test(x)).slice(0,2);if(cls.length)part+='.'+cls.map(CSS.escape).join('.');const parent=cur.parentElement;if(parent){const same=[...parent.children].filter(x=>x.localName===cur.localName);if(same.length>1)part+=`:nth-of-type(${same.indexOf(cur)+1})`;}parts.unshift(part);cur=parent;}return parts.join(' > ');};const move=e=>{const el=e.target;if(el===overlay)return;const r=el.getBoundingClientRect();Object.assign(overlay.style,{display:'block',left:`${r.left}px`,top:`${r.top}px`,width:`${r.width}px`,height:`${r.height}px`});};const key=e=>{if(e.key==='Escape')cleanup(null);};const click=e=>{e.preventDefault();e.stopPropagation();const el=e.target;const r=el.getBoundingClientRect();cleanup({selector:selectorFor(el),tag:el.localName,role:el.getAttribute('role')||'',text:(el.innerText||el.textContent||'').trim().replace(/\s+/g,' ').slice(0,180),ariaLabel:el.getAttribute('aria-label')||'',rect:{left:r.left,top:r.top,width:r.width,height:r.height},viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio}});};const cleanup=value=>{document.removeEventListener('mousemove',move,true);document.removeEventListener('click',click,true);document.removeEventListener('keydown',key,true);overlay.remove();resolve(value);};document.addEventListener('mousemove',move,true);document.addEventListener('click',click,true);document.addEventListener('keydown',key,true);});}
async function cropScreenshot(dataUrl,rect,viewport){const img=new Image();img.src=dataUrl;await img.decode();const sx=img.naturalWidth/viewport.width,sy=img.naturalHeight/viewport.height,margin=20;const x=Math.max(0,Math.floor((rect.left-margin)*sx)),y=Math.max(0,Math.floor((rect.top-margin)*sy)),right=Math.min(img.naturalWidth,Math.ceil((rect.left+rect.width+margin)*sx)),bottom=Math.min(img.naturalHeight,Math.ceil((rect.top+rect.height+margin)*sy));const canvas=document.createElement('canvas');canvas.width=Math.max(1,right-x);canvas.height=Math.max(1,bottom-y);canvas.getContext('2d').drawImage(img,x,y,canvas.width,canvas.height,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png');}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
init();
